name: Build Dummy Docker Image

on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Java Project
        run: mvn clean install
   
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/praveen-image:latest .
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/praveen-image:latest
